CREATE TABLE IF NOT EXISTS pets (
    id BIGSERIAL PRIMARY KEY,
    name VARCHAR(60) NOT NULL,
    species VARCHAR(20) NOT NULL,
    age INTEGER NOT NULL,
    race VARCHAR(50) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
